##  Import Data

In [6]:
import pandas as pd

# Membaca data dari file Excel
df = pd.read_excel('F:\PESANAN FASTWORK\MACHINE LEARNING\Siti Klasifikasi\BUMILS\BUMILS\Data BUMIL_new.xlsx', 'Sheet1')

# Menampilkan data
df

,No,Nama Ibu/Suami,Alamat,Umur,HPHT,TP,BB,TB,UK,LILA,Hemoglobin
0,1,Ibu Hamil 1,Desa Pasawahan,31 th,28/12/2022,2023-04-10 00:00:00,60,150,4 Mg,25,12
1,2,Ibu Hamil 2,Desa Pasawahan,22 th,19/11/2022,26/08/2023,50,160,7 mg,24,12
2,3,Ibu Hamil 3,Desa Pasawahan,32 th,2022-02-12 00:00:00,2023-09-09 00:00:00,55,150,5 mg,26,12
3,4,Ibu Hamil 4,Desa Pasawahan,23 th,16/10/2022,23/07/2023,46,155,12 mg,22,10
4,5,Ibu Hamil 5,Desa Pasawahan,28 th,2022-02-12 00:00:00,2023-09-09 00:00:00,67,155,6 mg,27,11
...,...,...,...,...,...,...,...,...,...,...,...
845,846,Ibu Hamil 846,Desa Benda,28 th,30/03/2023,22/02/2024,68,148,8 mg,29,11
846,847,Ibu Hamil 847,Desa Benda,22 th,20/04/2023,2024-10-03 00:00:00,35,135,6 mg,"23,5",10
847,848,Ibu Hamil 848,Desa Benda,28 th,2023-10-03 00:00:00,2024-11-02 00:00:00,43,150,10 mg,22,10
848,849,Ibu Hamil 849,Desa Benda,36 th,2023-04-04 00:00:00,28/02/2024,61,143,20 mg,28,12
849,850,Ibu Hamil 850,Desa Benda,28 th,2023-10-03 00:00:00,17/01/2024,60,163,7 mg,31,12

## Preprocessing

In [11]:
# Mengonversi kolom yang diperlukan ke tipe data numerik
df['Hemoglobin'] = pd.to_numeric(df['Hemoglobin'], errors='coerce')
df['LILA'] = pd.to_numeric(df['LILA'], errors='coerce')
df['BB'] = pd.to_numeric(df['BB'], errors='coerce')
df['TB'] = pd.to_numeric(df['TB'], errors='coerce')

# Menghitung IMT
df['IMT'] = df['BB'] / ((df['TB'] / 100) ** 2)

# Fungsi untuk mengkategorikan hemoglobin
def categorize_hemoglobin(hb):
    if hb <= 8:
        return 'Anemia Berat'
    elif 8 < hb <= 10.9:
        return 'Anemia Ringan'
    else:
        return 'Normal'

# Fungsi untuk mengkategorikan LILA
def categorize_LILA(lila):
    if lila < 23.5:
        return 'Kurang Gizi'
    elif 23.5 <= lila <= 33:
        return 'Gizi Cukup'
    else:
        return 'Gizi Lebih'

# Fungsi untuk mengkategorikan IMT
def categorize_IMT(imt):
    if imt < 18.5:
        return 'Kurus'
    elif 18.5 <= imt < 24.9:
        return 'Normal'
    elif 25 <= imt < 29.9:
        return 'Overweight'
    else:
        return 'Obesitas'

# Menambahkan kolom kategori
df['hemoglobin_kat'] = df['Hemoglobin'].apply(categorize_hemoglobin)
df['LILA_kat'] = df['LILA'].apply(categorize_LILA)
df['IMT_kat'] = df['IMT'].apply(categorize_IMT)

# Fungsi untuk membuat label gizi
def create_nutrition_label(row):
    if row['LILA_kat'] == 'Kurang Gizi' or row['hemoglobin_kat'] in ['Anemia Berat', 'Anemia Ringan'] or row['IMT_kat'] == 'Kurus':
        return 'Gizi Kurang'
    elif row['IMT_kat'] in ['Overweight', 'Obesitas']:
        return 'Gizi Lebih'
    else:
        return 'Gizi Cukup'

# Menambahkan kolom label gizi
df['nutrition_label'] = df.apply(create_nutrition_label, axis=1)

# Menampilkan data dengan kolom baru
df

,No,Nama Ibu/Suami,Alamat,Umur,HPHT,TP,BB,TB,UK,LILA,Hemoglobin,hemoglobin_kat,LILA_kat,IMT,IMT_kat,nutrition_label
0,1,Ibu Hamil 1,Desa Pasawahan,31 th,28/12/2022,2023-04-10 00:00:00,60.0,150,4 Mg,25.0,12.0,Normal,Gizi Cukup,26.666667,Overweight,Gizi Lebih
1,2,Ibu Hamil 2,Desa Pasawahan,22 th,19/11/2022,26/08/2023,50.0,160,7 mg,24.0,12.0,Normal,Gizi Cukup,19.531250,Normal,Gizi Cukup
2,3,Ibu Hamil 3,Desa Pasawahan,32 th,2022-02-12 00:00:00,2023-09-09 00:00:00,55.0,150,5 mg,26.0,12.0,Normal,Gizi Cukup,24.444444,Normal,Gizi Cukup
3,4,Ibu Hamil 4,Desa Pasawahan,23 th,16/10/2022,23/07/2023,46.0,155,12 mg,22.0,10.0,Anemia Ringan,Kurang Gizi,19.146722,Normal,Gizi Kurang
4,5,Ibu Hamil 5,Desa Pasawahan,28 th,2022-02-12 00:00:00,2023-09-09 00:00:00,67.0,155,6 mg,27.0,11.0,Normal,Gizi Cukup,27.887617,Overweight,Gizi Lebih
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,846,Ibu Hamil 846,Desa Benda,28 th,30/03/2023,22/02/2024,68.0,148,8 mg,29.0,11.0,Normal,Gizi Cukup,31.044558,Obesitas,Gizi Lebih
846,847,Ibu Hamil 847,Desa Benda,22 th,20/04/2023,2024-10-03 00:00:00,35.0,135,6 mg,NaN,10.0,Anemia Ringan,Gizi Lebih,19.204390,Normal,Gizi Kurang
847,848,Ibu Hamil 848,Desa Benda,28 th,2023-10-03 00:00:00,2024-11-02 00:00:00,43.0,150,10 mg,22.0,10.0,Anemia Ringan,Kurang Gizi,19.111111,Normal,Gizi Kurang
848,849,Ibu Hamil 849,Desa Benda,36 th,2023-04-04 00:00:00,28/02/2024,61.0,143,20 mg,28.0,12.0,Normal,Gizi Cukup,29.830310,Overweight,Gizi Lebih
849,850,Ibu Hamil 850,Desa Benda,28 th,2023-10-03 00:00:00,17/01/2024,60.0,163,7 mg,31.0,12.0,Normal,Gizi Cukup,22.582709,Normal,Gizi Cukup

In [12]:
# Export data
df.to_excel("databumil_clean.xlsx", index=False)